-- 입양 시각 구하기(2)
SET @HOUR = -1;
SELECT (@HOUR := @HOUR +1) AS HOUR, (
    SELECT COUNT(*)
    FROM ANIMAL_OUTS
    WHERE @HOUR = DATE_FORMAT(DATETIME, '%k')
) as COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23;