-- 보호소에서 중성화한 동물
SELECT a.ANIMAL_ID AS ANIMAL_ID, a.ANIMAL_TYPE as ANIMAL_TYPE, a.NAME as NAME
FROM ANIMAL_INS a INNER JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID 
WHERE a.SEX_UPON_INTAKE LIKE "Intact%" AND b.SEX_UPON_OUTCOME NOT LIKE "Intact%"
